name: Demo Action

on:
  pull_request:
    branches:
      - main

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Demo Script
        run: echo "Hello, this is a GitHub Action test!"
